codecov:
  notify:
    require_ci_to_pass: no

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        enabled: no

ignore:
  - "**/*Macros.scala"        # Scala Macros coverage cannot be evaluated
  - "**/[\.]?js/src/**.scala" # Scala.js code
  - "airframe-benchmark/**/*.scala" # Do not check benchmark code coverage
