name: Airframe
baseurl: /airframe
description: Lightweight Building Blocks for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 19.9.8+15-ce15cb43-SNAPSHOT
org: org.wvlet.airframe
markdown: kramdown
