name: Airframe
baseurl: /airframe
description: Lightweight Building Blocks for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 19.10.0+1-77c85b30-SNAPSHOT
org: org.wvlet.airframe
markdown: kramdown
