name: Doc

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'website/**'
      - '.github/workflows/doc.yml'

jobs:
  doc:
    name: Update docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Git
        run: |
          git config --global user.email "leo@xerial.org"
          git config --global user.name "Taro L. Saito"
          git config --global push.default simple
      - name: Setup Deploy
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-mdocs-${{ hashFiles('docs/**') }}
          restore-keys: |
            ${{ runner.os }}-mdocs-${{ hashFiles('docs/**') }}-
            ${{ runner.os }}-mdocs-
      - name: Publish doc
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        run: ./sbt docs/docusaurusPublishGhpages
