name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish_jvm:
    name: Publish Scala JVM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-gpg@v2 # Necessary for using GPG1
      - name: Setup GPG
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
        run: echo $PGP_SECRET | base64 --decode | gpg --import --batch --yes
      - name: Build bundle
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_USERNAME: '${{ secrets.SONATYPE_USER }}'
          SONATYPE_PASSWORD: '${{ secrets.SONATYPE_PASS }}'
        run: ./sbt "; + projectJVM2_13/publishSigned; + projectJVM2_12/publishSigned; sonatypeBundleRelease"
