name: Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  publish_jvm:
    name: Publish Scala JVM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Bundle
        run: ./sbt "; + projectJVM2_13/publishSigned; + projectJVM2_12/publishSigned; sonatypeBundleRelease"
  publish_js:
    name: Publish Scala.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build for Scala.js 0.6.x
        run: SCALA_JS_VERSION=0.6.29 ./sbt "projectJS/publishSigned"
      - name: Build for Scala.js 1.0.x
        run: SCALA_JS_VERSION=1.0.0-M8 ./sbt "; projectJS/publishSigned; sonatypeBundleRelease"
