name: CI

on: [push]

jobs:
  code_format:
    name: Code Format Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Code Format Check
      run: ./scalafmt --test
  test_2_12:
    name: Scala 2.12 test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Scala 2.12 test
      run: ./sbt projectJVM/test
  test_2_13:
    name: Scala 2.13 test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Scala 2.13 test
      run: ./sbt ++2.13.1 projectJVM/test
  test_2_11:
    name: Scala 2.11 test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Scala 2.11 test
      run: ./sbt ++2.11.12 projectJVM/test
  test_js:
    name: Scala.js test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Scala.js test
      run: ./sbt projectJS/test
