name: CI

on: [push]

jobs:
  code_format:
    name: Code Format Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Code Format Check
      run: ./scalafmt --test
  test:
    name: Scala JVM Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala-version: [2.12.10, 2.11.12]
    steps:
    - uses: actions/checkout@v1
    - name: Scala ${{ matrix.scala-version}} JVM test
      run: ./sbt ++${ matrix.scala-vesrion }} projectJVM/test
  test_2_13:
    name: Scala 2.13 test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Scala 2.13 test
      run: ./sbt ++2.13.1 projectJVM2_13/test
  test_js:
    name: Scala.js test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Scala.js test
      run: ./sbt projectJS/test
